services:
  postgres:
    image: postgres:16-alpine
    container_name: postgres-sandwich
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    networks:
      - sandwich-net

volumes:
  pgdata:

networks:
  sandwich-net:
    driver: bridge